Ripes GUI works

diff --git a/cs1952y-run-docker b/cs1952y-run-docker
--- a/cs1952y-run-docker
+++ b/cs1952y-run-docker
@@ -77,6 +77,25 @@ create_network() {
   docker network create -d bridge $network_name
 }
 
+set_xhost() {
+  # Check if 'xhost' command is available
+  if ! command -v xhost &> /dev/null; then
+    echo "xhost command not found. X11 forwarding might not work."
+    return
+  fi
+
+  case "$(uname)" in
+    "Linux")
+      xhost +local:docker
+      ;;
+    "Darwin")
+      xhost +localhost
+      ;;
+    "CYGWIN"*|"MINGW32"*|"MSYS"*|"MINGW"*)
+      ;;
+  esac
+}
+
 remove_containers() {
   echo "Removing all existing cs1952y containers..."
   docker ps -a -f name=cs1952y --format "{{.ID}}" | while read -r line; do
@@ -97,10 +116,12 @@ start_new_container() {
       --platform $platform \
       --privileged \
       --cap-add=SYS_PTRACE --cap-add=NET_ADMIN --security-opt seccomp=unconfined \
+      -m 16g \
       -v "$maindir/home":/home/cs1952y-user \
       -w "/home/cs1952y-user" \
       -p "0.0.0.0:9095:9095" \
       --network "$network_name" \
+      $displayarg$x11mountarg \
       $netarg$sshenvarg $tag
 }
 
@@ -153,6 +174,27 @@ if [[ -n "$maindir" ]]; then
       vexec docker exec -it"$sshenvarg" "$image" /bin/bash
   fi
 fi
+
+# set up X11 forwarding
+displayarg=""
+x11mountarg=""
+case "$(uname)" in 
+  "Linux")
+    displayarg="-e DISPLAY"
+    x11mountarg="-v /tmp/.X11-unix:/tmp/.X11-unix"
+    ;;
+  "Darwin")
+    displayarg="-e DISPLAY=host.docker.internal:0"
+    ;;
+  "CYGWIN"*|"MINGW32"*|"MSYS"*|"MINGW"*)
+    displayarg="-e DISPLAY=host.docker.internal:0.0"
+    ;;
+  *)
+    echo "Unsupported OS for X11 forwarding"
+    ;;
+esac
+
+set_xhost
 
 # expose ports for Docker container
 netarg=""
